# Generated by Django 4.1.3 on 2022-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0004_rename_valor_pedido_valorpedido_pedido_valorproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='000000', max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao-credito', 'Crédito'), ('cartao-debito', 'Débito')], default='dinheiro', max_length=20, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statusPedido',
            field=models.CharField(choices=[('separando', 'Separando'), ('concluido', 'Concluído'), ('preparando-entrega', 'Preparando'), ('saiu-entrega', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='separando', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorPedido',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorProduto',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Produto'),
        ),
    ]
