# Generated by Django 4.1.3 on 2022-11-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0006_pedido_quantidadeproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('valorPedido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Total')),
                ('valorProduto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Produto')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('quantidadeProduto', models.IntegerField(verbose_name='Quantidade Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padaria.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padaria.produto')),
            ],
        ),
    ]
