# Generated by Django 4.1.3 on 2022-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0007_itenspedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenspedido',
            options={'verbose_name': 'Items Pedido', 'verbose_name_plural': 'Items Pedido'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidadeProduto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valorProduto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='padaria.ItensPedido', to='padaria.produto'),
        ),
    ]
