# Generated by Django 4.1.3 on 2022-11-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0008_alter_itenspedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidadeProduto',
            field=models.IntegerField(null=True, verbose_name='Quantidade Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valorProduto',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor Produto'),
        ),
    ]
